name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
          - 20

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.7

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run build

      - run: npm test

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
